### ISSUE TITLE
how to satisfy luacheck for unused variables

### ISSUE THREAD

**Issue by SwissalpS** [minetest-beerchat/beerchat#11]
Is there a cleaner way to solve this than adding lines:
unused_var = unused_var

**Comment by coil0** [comment]
Changing the name to `_` is cleaner than adding lines, but for all of them except the `on_forced_join` callback you can instead remove the parameters since they're at the end of the parameter list.

**Comment by thomasrudin** [comment]
don't take the luacheck warnings too serious :stuck_out_tongue: if it gets in the way the `.luacheckrc` can still be adapted, for example with a `unused = false`:

https://github.com/minetest-mods/drawers/blob/master/.luacheckrc#L2

**Comment by SwissalpS** [comment]
> or `unused_args`

that sounds like what I was looking for, but on a per file basis so luacheck still finds those we may have missed and wanted.

we can still add the full signature as comment for future devs to have it easier to add back if they should be needed.

**Comment by SwissalpS** [comment]
I've added:
`files["jail.lua"] = { unused_args = false }`
which silences these warnings for jail.lua only
