### ISSUE TITLE
Colorize channel name if the message is not on the default channel

### ISSUE THREAD

**Issue by Emojigit** [minetest-beerchat/beerchat#122]
This makes messages between default and custom channels distinct.

Alternative: colorize the messages themself

**Comment by OgelGames** [comment]
Like this?

![image](https://github.com/user-attachments/assets/0fc6656a-5180-4f2b-844d-6066314393ab)

You can set the color of a channel when you create it: https://github.com/mt-mods/beerchat/blob/master/doc/manual.md

**Comment by S-S-X** [comment]
Additionally, while it might not exactly be obvious at first, you can use `/cc` command to edit channel properties and this include color setting.

You however must supply all properties like channel password while doing this and you have to be channel owner. 
* Implementation details: #78

**Comment by S-S-X** [comment]
Comment / reopen if these wont be enough to solve the issue.
