### ISSUE TITLE
Notify player if whispers cant be heard by anyone

### ISSUE THREAD

**Issue by S-S-X** [minetest-beerchat/beerchat#13]
Count players that received message and if count is less than 1 then send some chat message back to whisperer telling that nobody could heard their whispers.

**Comment by S-S-X** [comment]
Opening this again, sorry for misleading description but there must be at least 2 players hearing whisper: whisperer and other player.

**Comment by S-S-X** [comment]
Also, please do not check if whispering player is other_player because that will hide actual message from player who sent message, instead either count or add success if player != other_player.

**Comment by BuckarooBanzay** [comment]
> Opening this again, sorry for misleading description but there must be at least 2 players hearing whisper: whisperer and other player.

Thanks for pointing that out :+1: 

> Also, please do not check if whispering player is other_player because that will hide actual message from player who sent message, instead either count or add success if player != other_player.

That would have been my first solution :yum:
