### ISSUE TITLE
beerchat is ignoring priv shout

### ISSUE THREAD

**Issue by Festus1965** [minetest-beerchat/beerchat#15]
when fast want to silence a bad word player or to teach to be less spamming, 
normally I just took "/revoke player shout"

but beerchat seam to ignore this priv shout setting

where to implementate if I do myself - or I missed a setting for this ?

**Comment by S-S-X** [comment]
Through your own customization you can register `before_send` callback and `return false` if player is not allowed to send messages. Something like this:
```lua
-- Customization to prevent chatting without shout privilege
local function check_if_player_can_chat(name, message, channel)
  return minetest.check_player_privs(name, {shout=true})
end

beerchat.register_callback("before_send", check_if_player_can_chat)
```

However I think maybe `shout` priv should be always checked and prevent all chatting if player does not have shout.

Another option to silence players is to use jail enabled by setting config value `beerchat.enable_jail` and then using `/chat_jail player1 player2 player3 ...` command and `/chat_unjail player2 player3 ...`.

**Comment by Festus1965** [comment]
I try ... as not sure what files ... coding is long time ago and not much used.
But I hope much more this will be fixed in the original here, for everyone, as it can't be to ignore privs shout
tomorrow, I will see ... fresh head, time ... and maybe no gamer in for a chance ...

**Comment by BuckarooBanzay** [comment]
The main action for the message parsing from players to channels is done here:
https://github.com/minetest-beerchat/beerchat/blob/9700fc20e67fe41e2179de5028d409e0f07c9dff/message.lua#L42-L70

Marking this as a (low prio) bug: the `shout` shout really be needed to send messages on channels

**Comment by BuckarooBanzay** [comment]
@Festus1965 i've added a priv-check in bcf61798086c9a65080502f8f83ee8c6040cc3d5 but i haven't tested it yet

**Comment by Festus1965** [comment]
will try it, code is in, but not restarted ... maybe today, with going back to 5.2.0

Do yo have any Idea how many player I banned, as silenced them as of chat-spam and thought they use a hacked client as they was still able to chat ??? and I thought beerchat IS respecting the /priv shout ?
So far now I counted 16 players ... oh oh

**Comment by BuckarooBanzay** [comment]
:shrug:
