### ISSUE TITLE
add /mute4all command

### ISSUE THREAD

**Issue by SwissalpS** [minetest-beerchat/beerchat#5]
Make it a moderator only command that makes the player muted to all players. Leaving the troll in the dark.

**Comment by thomasrudin** [comment]
Sounds good, but the `beerchat` mod only mutes the troll on the currently online players iirc.
So all others joining after the `/mute4all` command will still see the troll's messages...

Alternative: there is a `shout` priv for that, maybe we can let moderators grant/revoke that.

IMO: i rather kick/tempban trolls to make a spot free for a behaving player..

**Comment by SwissalpS** [comment]
> So all others joining after the `/mute4all` command will still see the troll's messages...

So true. That defeats this idea :)
