### ISSUE TITLE
sending PM to multiple players does not seem to work

### ISSUE THREAD

**Issue by SwissalpS** [minetest-beerchat/beerchat#6]
Do we need to fix this at all?

**Comment by SwissalpS** [comment]
'@playerOne,playerTwo,player3 message'
results in only playerOne getting message
have not tried /msg myself, but heard it does not work either.

**Comment by S-S-X** [comment]
I'd say no for this. This feels like anti-feature and should not be implemented in chat.

**Comment by thomasrudin** [comment]
I always thought PM means private message, something you send to **one** other person...
**IMO:** channels are the tool for 1:n communication, PM's are 1:1 messages

**Comment by SwissalpS** [comment]
agree. It seems that vanilla supports that, but it does not have channels.
